apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - name: jenkins-web
    port: 8080
  - name: jenkins-50000
    port: 50000
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: jenkins
  namespace: default
spec:
  serviceName: jenkins-svc
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins
        volumeMounts:
          - name: jenkinsData
            mountPath: /var/jenkins_home
      volumes:
        - name: jenkinsData
          hostPath:
            path: /c/Users/tta/.jenkins